export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';
export const SELECT_USER= 'SELECT_USER';
export const SELECT_ALL_USER= 'SELECT_ALL_USER';

export const LOAD_TURNS_SUCCESS = 'LOAD_TURNS_SUCCESS';
export const UPDATE_TURN_SUCCESS= 'UPDATE_TURN_SUCCESS';
export const SELECT_TURN= 'SELECT_TURN';
export const SELECT_ALL_TURN= 'SELECT_ALL_TURN';

export const LOAD_TESTS_SUCCESS = 'LOAD_TESTS_SUCCESS';
export const UPDATE_TEST_SUCCESS= 'UPDATE_TEST_SUCCESS';
export const SELECT_TEST= 'SELECT_TEST';
export const SELECT_ALL_TEST= 'SELECT_ALL_TEST';

export const SIGN_UP_TO_TURN_SUCCESS= 'SIGN_UP_TO_TURN_SUCCESS';
export const GET_CURRENT_TURN_SUCCESS= 'GET_CURRENT_TURN_SUCCESS';

export const UPDATE_SIGNUP_DATA_SUCCESS= 'UPDATE_SIGNUP_DATA_SUCCESS';
export const LOAD_SIGNUP_DATAS_SUCCESS= 'LOAD_SIGNUP_DATAS_SUCCESS';

export const GET_USER_TEST_SUCCESS= 'GET_USER_TEST_SUCCESS';
export const UPDATE_USER_TEST_SUCCESS= 'UPDATE_USER_TEST_SUCCESS';
export const LOAD_USER_SIGNUP_TEST_SUCCESS= 'LOAD_USER_SIGNUP_TEST_SUCCESS';

export const UPLOAD_SIGNUP_STATEMENT_SUCCESS= 'UPLOAD_SIGNUP_STATEMENT_SUCCESS';
export const GET_SIGNUP_STATEMENT_SUCCESS= 'GET_SIGNUP_STATEMENT_SUCCESS';

export const FINALIZE_SIGNUP_SUCCESS= 'FINALIZE_SIGNUP_SUCCESS';
export const GET_USER_TURN_SUCCESS= 'GET_USER_TURN_SUCCESS';








