export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';
export const SELECT_USER= 'SELECT_USER';
export const SELECT_ALL_USER= 'SELECT_ALL_USER';

export const LOAD_TURNS_SUCCESS = 'LOAD_TURNS_SUCCESS';
export const UPDATE_TURN_SUCCESS= 'UPDATE_TURN_SUCCESS';
export const SELECT_TURN= 'SELECT_TURN';
export const SELECT_ALL_TURN= 'SELECT_ALL_TURN';




