const signupDatas = [
  {
    id: "1",
    user_id: "1",
    name: 'Kis Benő',
    vallalkozas_szekhelye: '',
    tobbsegi_tulajdon_mas_vallalkozasban: '0',
    birth_name: '',
    birth_date: 644796000000,
    birth_place: 'Miskolc',
    mothers_name: '',
    permanent_address: '',
    temporary_address: '',
    postal_address: '',
    phone: '',
    email: "beno@bn.hu",
    legmagasabb_iskolai_vegzettseg: '',
    legmagasabb_iskolai_vegzettseg_eve: '',
    allaskeresokent_regisztralt: '',
    allaskeresokent_regisztralt_datuma: '',
  },
  {
    id: "2",
    user_id: "123",
    name: 'Kis Piroska',
    vallalkozas_szekhelye: '',
    tobbsegi_tulajdon_mas_vallalkozasban: '0',
    birth_name: '',
    birth_date: 644796000000,
    birth_place: 'Sopron',
    mothers_name: '',
    permanent_address: '',
    temporary_address: '',
    postal_address: '',
    phone: '',
    email: "kis@gmail.hu",
    legmagasabb_iskolai_vegzettseg: '',
    legmagasabb_iskolai_vegzettseg_eve: '',
    allaskeresokent_regisztralt: '',
    allaskeresokent_regisztralt_datuma: '',
  },
];

export default signupDatas;
