export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED';
export const SIGNUP_FINALIZED = 'SIGNUP_FINALIZED';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';

export const SIGNUP_STATEMENT_UPLOADED = 'SIGNUP_STATEMENT_UPLOADED';
export const SIGNUP_STATEMENT_VALID = 'SIGNUP_STATEMENT_VALID';
export const SIGNUP_TEST_SAVED = 'SIGNUP_TEST_SAVED';
export const SIGNUP_TEST_VALID = 'SIGNUP_TEST_VALID';
export const SIGNUP_DATA_SAVED = 'SIGNUP_DATA_SAVED';
export const SIGNUP_DATA_VALID = 'SIGNUP_DATA_VALID';
export const SIGNUP_AGREEMENTS_ACCEPTED = SIGNUP_AGREEMENTS_ACCEPTED;


