export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED';
export const SIGNUP_STATEMENT_UPLOADED = 'SIGNUP_STATEMENT_UPLOADED';
export const SIGNUP_TEST_COMPLETED = 'SIGNUP_TEST_COMPLETED';
export const SIGNUP_DATA_COMPLETED = 'SIGNUP_DATA_COMPLETED';
export const SIGNUP_STATEMENTS_ACCEPTED = 'SIGNUP_STATEMENTS_ACCEPTED';


